# Introduction

The CoronaNet COVID-19 Government Response Tracker Database provides fine-grained, dyadic data on policy actions taken by governments across the world since the Chinese government reported the COVID-19 outbreak on December 31, 2019. The dataset presented here covers all policy actions for X number of countries up until XX XX, 2020, for a total of YY number of events.^[Our data collection efforts are still ongoing. For the most current, up to date version of the dataset, please visit http://website_name.com]  

The rapid and devastating spread of the coronavirus has put in stark relief the previously invisible connections among different countries and people. Our dataset illuminates a countervailing kind of network --- it documents not only what actions governments have taken against COVID-19, but how these actions have targeted other geographical regions and the people and resources within them over time. The data, which is publicly available, will allow us to understand among other things, how the effectiveness of different government policies may vary over time or depending on policy actions taken by other governments. 

More specifically, the CoronaNet database collects data on government policy actions taken against the coronavirus across the following dimensions and tracks them over time:

+ The type of government policy implemented (e.g. quarantine, closure of schools [15 total] )
+ The level of government initiating the action (e.g. national, provincial, municipal etc.)
+ The geographical target of the policy action, if applicable (e.g. national, provincial, municipal etc.)
+ The human or material target of the policy action, if applicable (e.g. travlers, ventilators)
+ The directionality of the policy action, if applicable (e.g., inbound, outbound, both)
+ The mechanism of travel that the policy action targets, if applicable (e.g. flights, trains)
+ The compliance with the policy action (e.g. mandatory, volulntary)
+ The timing of the policy action (e.g. date announced, date implemented)

In what follows, we describe in greater detail the methodology we employed to collect this data, a description of the data, and an application of the data [....] For more information on the exact variables collected, please reference the codebook in the appendix. 
