---
title: "CoronaNet COVID-19 Government Response Tracker Database"
date: "3/28/2020"
toc: false

---
# Abstract {-}

The CoronaNet COVID19 Government Response Tracker documents government policies adopted in response to the COVID-19 virus. The data yields fine-grained, directed dyadic information on, among other things, (1) which governments at all levels (e.g. national, provincial, city/municipal) have taken policy actions against COVID-19 (2) what policy actions they have taken (e.g. travel bans, strengthening public health sector) (3) what geographical regions they have targeted (e.g. countries, provinces) (4) who or what they are targeting (e.g. foreigners, ventilators) (5) what the compliance mechanism is (e.g. mandatory or voluntary) (6) who the enforcing body of a policy is and (7) when the policy action was announced, implemented and where applicable, expected to end. The data, which was generated using crowd-sourcing with reliability and validity checks, is made publicly available, can help researchers understand among other things, the effectiveness of different measures,as well as what factors drive government policy towards COVID-19. 

