---
title: "CoronaNet Database: Governmental Responses towards COVID-19"
date: "04/06/2020"
toc: false

---
# Abstract {-}

The CoronaNet Research Project compiles a database that documents government policies adopted in response to the COVID-19 virus. The data yields fine-grained, directed dyadic information on, among other things, (1) which governments at all levels (e.g. national, provincial, city/municipal) have taken policy actions against COVID-19 (2) what policy actions they have taken (e.g. travel bans, strengthening public health sector) (3) what geographical regions they have targeted (e.g. countries, provinces) (4) who or what they are targeting (e.g. foreigners, ventilators) (5) what the compliance mechanism is (e.g. mandatory or voluntary) (6) who the enforcing body of a policy is and (7) when the policy action was announced, implemented and where applicable, expected to end. The data subsumes more than 5000 policies of XXX countries, was generated by a research consortium of 180 political and social science scholars and underlies extensive reliability as well as validity checks. Our dataset is publicly available, can help researchers understand among other things, the effectiveness of different measures, differences between regime types and states, as well as what factors drive government policy towards COVID-19. 

