\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={CoronaNet Government Response Database: A Dyadic, Hand-Coded Dataset of World-wide Responses to the COVID-19 Pandemic},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{CoronaNet Government Response Database: A Dyadic, Hand-Coded Dataset of World-wide Responses to the COVID-19 Pandemic}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{true \\ true \\ true \\ true \\ true}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{4/5/2020}

\usepackage{tikzit}
\input{basic_oval.tikzstyles}
\linespread{1.6}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\begin{document}
\maketitle
\begin{abstract}
In this paper we present an initial release of a large hand-coded dataset of more than 5,000 separate policy announcements from governments around the world. The data are being made publicy available at our website and Github account (see footnote below), in combination with COVID-19 testing data and country-level covariates. The data are intended to be used by researchers for the purpose of studying the interaction of disease outbreaks and government responses, in addition to the possible determinants of these varying levels of policy strictness. For that purpose, we also include a time-varying severity index of government responses obtained through a time-varying Bayesian latent variable model. \footnote{or the most current, up to date version of the dataset, please visit \url{http://coronanet-project.org} and also our Github page at \url{https://github.com/saudiwin/corona_tscs}.}
\end{abstract}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

<<<<<<< HEAD
Governments all around the world have implemented an astonishing variety of policies in reaction to the COVID-19 pandemic. Policy makers and researchers however, have to date lacked access to the quality, up-to-date data they need for conducting rigorous analyses of whether, how, or to what degree these fast changing policies have worked in brunting the health, political and economic effects of the coronavirus. To address this concern, we present in this paper the CoronaNet COVID-19 Government Response Database, which provides fine-grained, dyadic data on policy actions taken by governments across the world since the Chinese government reported the COVID-19 outbreak on December 31, 2019. The dataset presented here covers all policy actions for 193 of countries\footnote{Note, we will include additional countries in future versions of the dataset.} up until 2020-04-12, for a total of 6782 events.
=======
The CoronaNet COVID-19 Government Response Tracker Database provides fine-grained, dyadic data on policy actions taken by governments across the world since the Chinese government reported the COVID-19 outbreak on December 31, 2019. The dataset presented here covers all policy actions for 188 of countries up until 2020-04-06, for a total of 4695 events.
>>>>>>> d7438a47fcf5fa95add9dbd70877c58facbca097

The rapid and devastating spread of the SARS-CoV-2 virus has put in stark relief the previously invisible connections among different countries and people. Our dataset illuminates a countervailing kind of network --- it documents not only what actions governments have taken against COVID-19, but how these actions have targeted other geographical regions and the people and resources within them over time. The data, which is publicly available, will allow us to understand among other things, how the effectiveness of different government policies may vary over time or depending on policy actions taken by other governments.

More specifically, the CoronaNet database collects data on government policy actions taken against the coronavirus across the following dimensions and tracks them over time:

\begin{itemize}
\tightlist
\item
  The type of government policy implemented (e.g.~quarantine, closure of schools {[}15 total{]} )
\item
  The level of government initiating the action (e.g.~national, provincial, municipal etc.)
\item
  The geographical target of the policy action, if applicable (e.g.~national, provincial, municipal etc.)
\item
  The human or material target of the policy action, if applicable (e.g.~travlers, ventilators)
\item
  The directionality of the policy action, if applicable (e.g., inbound, outbound, both)
\item
  The mechanism of travel that the policy action targets, if applicable (e.g.~flights, trains)
\item
  The compliance with the policy action (e.g.~mandatory, volulntary)
\item
  The timing of the policy action (e.g.~date announced, date implemented)
\end{itemize}

<<<<<<< HEAD
Data on government reactions the COVID-19 pandemic can not only help us understand which policies are more effective in addressing the spread and health outcomes of COVID-19, it can also forward our knowledge of, inter alia, the relative responsiveness of different political regime types (Przeworski, Stokes, and Manin 1999), the politics of crisis management (Boin et al. 2016), the development of financial crises (Kindleberger and Aliber 2011) and, the sociology of natural disasters (Tierney 2007). Moreover, given the exogenous timing of the initial COVID-19 outbreak in China, government policies made in reaction to the COVID-19 pandemic constitute the single largest natural experiment in recent memory, allowing researchers to improve causal inference in any number of fields. Indeed, how governments react to the COVID-19 epidemic will have long-lasting implications on a wide-range of social phenomena, from political institutions, (Pierson 2000) economic development (Nunn 2009) to environmental outcomes (Dasgupta et al. 2002). While scholars have always sought to understand how large-scale historical events have shaped contemporary phenomena, modern technological tools allow us to document such events more quickly and more precisely than ever before.

In what follows, we provide a description of the data, as well the application of our data in modeling the level of government policy activity over time. Using a Bayesian dynamic item-response theory model, we produce a statistically valid index that ranks countries in terms of their response to the pandemic, and also shows how quickly policy responses have changed over time. We document clear evidence of rapid policy diffusion of harsh measures opposing the virus, indicating some of the most extensive evidence of this type of diffusion ever documented. We then outline the methodology we used to collect the data.

\hypertarget{dataset-overview}{%
\section{Dataset Overview}\label{dataset-overview}}

Here we describe the variables that the CoronaNet project is able to provide and then present some descriptive statistics to illustrate the distribution of some key variables in the dataset. Each policy records at the minimum, the following monadic information : the policy type (\texttt{type}), the name of the country from which a policy orginiates (\texttt{country})\footnote{If the policy originates from a subnational unit of government, e.g.~a province or city, that information is also documented.}, the degree to which a policy must be complied with (\texttt{compliance}), the entity enforcing the policy (\texttt{enforcer}), and the date a policy is announced (\texttt{date\_annouced}), implemented (\texttt{date\_start}) and ends (\texttt{date\_end}).\footnote{Note that sometimes policies are announced without a pre-determined end date. In those cases, this field is left blank} When a policy is dyadic in nature, the database further documents information about the geographic target of the policy (\texttt{target\_geog\_level}; \texttt{target\_region}, \texttt{target\_country})\footnote{Future versions of the dataset will also include information about if the target was a province or state (\texttt{target\_province}), a city or municipality (\texttt{target\_city}), or another subnational unit (e.g.~county, university)}, the human or material target of a policy (\texttt{target\_who\_what}), the directional flow of the policy (\texttt{target\_direction}), and the mechanism of travel (\texttt{target\_mechanism}). Where applicable, all of the information documented above is also provided qualitatively in the \texttt{event\_description} variable and each record is identified by a unique \texttt{record\_id}. Table \ref{tab:vardesc} provides an overview of the different variables in our dataset, a brief description of what underyling concept each variable aims to capture, and the values that each variable can take on.\footnote{Note that while Table \ref{tab:vardesc} provides an overview of the version of the dataset we have currently made available, future versions of the dataset will also include more detailed information for some policy categories. For example, among other things, we are also collecting information on the types of `health resources' (e.g.~masks, hospitals, doctors ) and types of `restrictions of non-essential business activities' (e.g.~retail businesses, restaurants/bars). Where applicable, we are also collecting information on the volume of a certain policy (e.g.~the number of masks, hospitals and doctors.)}

\begingroup\fontsize{10}{12}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}[para]
\small
\item \textit{Note: } 
\item Variables in the dataset not listed above include: record\_date (when the record entered into our data), link (a link to at least one source for the policy), init\_country\_level (whether a policy came from a national level or sub-national unit)
\item[*] The variables which document the exact geographical targets in the dataset are as follows: target\_region (documents targeted regional grouping, e.g. Schengen region), target\_country (documents targeted country), target\_province (documents targeted province/state)
\end{TableNotes}
\begin{longtable}{>{\bfseries\raggedright\arraybackslash}p{3.5cm}>{\raggedright\arraybackslash}p{5cm}>{\raggedright\arraybackslash}p{8.5cm}}
\caption{\label{tab:vardesc}Description of Variables in CoronaNet Government Reponse Dataset}\\
\toprule
\textbf{Variable Name} & \textbf{Description} & \textbf{Values}\\
\midrule
\rowcolor{gray!6}  record\_id & A unique identifier for each policy record & This variable takes on a numeric value. A unique record ID is given for the following unit of analysis: country-type-date\_announced\\
policy\_id & A unique identifier for each policy record as it is updated over time & This variable takes on a numeric value. A unique policy ID encompasses different record IDs that change over time with regards to either the strength or time duration of the underlying policy.\\
\rowcolor{gray!6}  event\_description & This variable provides a qualtiative summary of the documented policy & All qualitative descriptions document at a minimum the following information: the policy type (type), the name of the country from which a policy originates (country); the date a policy is implemented (date\_start) and if applicable:  the country or region that a policy is targeted towards (target\_country), the type of people or resources a policy is targeted towards (target\_who\_what), when a policy is slated to end (date\_end)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Monadic Variables}}\\
\hspace{1em}type & This variable documents the policy action initiated. It can take on only one of the following values: & Declaraction of Emergency, Quarantine, External Border Restrictions, Internal Border Restrictions, Restrictions of Mass Gatherings, Social Distancing, Curfew, Closure of Schools, Restriction of Non-Essential Government Services, Restriction of Non-Essential Businesses, Health Monitoring, Health Testing, Health Resource, Public Awareness Campaigns, New Task Force or Bureau, Other\\
\rowcolor{gray!6}  \hspace{1em}country & This variable documents the country from which a policy initiates, where applicable, and can take on only one of the following values: & National, Provincial/State, Municipality/City, Other governmental unit\\
\hspace{1em}compliance & This variable documents degree to which a policy must be complied with and can take on one or more of the following values: & Mandatory with Legal Penalties, Mandatory with Fines, Mandatory with Excpetions, Recommended/Voluntary\\
\rowcolor{gray!6}  \hspace{1em}enforcer & This variable documents the entity enforcing a policy and can take on one or more of the following values: & National Government, Ministry/Department of Health, Military, Provincial/State Government, Municipal/City Government, Police, Other\\
\hspace{1em}date\_announced & This variable documents the date when a policy was announced, it takes on the following format: & Month-Day-Year\\
\rowcolor{gray!6}  \hspace{1em}date\_start & This variable documents the date when a policy is implemented, it takes on the following format: & Month-Day-Year\\
\hspace{1em}date\_end & This variable documents the date when a policy is slated to end, where applicable, it takes on the following format: & Month-Day-Year\\
\rowcolor{gray!6}  \addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Dyadic Variables}}\\
\hspace{1em}target\_geog\_level & This variable documents the geographical target of the policy. It can take on of the following variables (The exact geographical targets are also documented in other variables* in the dataset): & All countries, One or more countries and one or more regional groupings, One or more countries, but not all countries, One or more regional groupings, A geographical or administrative unit within a country\\
\hspace{1em}target\_who\_what & This variable documents the human or material targets of a policy, where applicable, and can take on only one of the following values: & All (Travelers + Residents), All Travelers (Citizen Travelers + Foreign Travelers), Citizen Travelers, Foreign Travelers, All Residents (Citizen Residents + Foreign Residents), Citizen Residents, Foreign Residents, All Foreign Nationals, All Citizens, Health Staff, Health-related Supplies\\
\rowcolor{gray!6}  \hspace{1em}target\_direction & This variable documents the direction of travel a policy targets, where applicable, and can take on only one of the following values: & Inbound, Outbound, Inbound/Outbound\\
\hspace{1em}travel\_mechanism & This variable documents the mode of travel a policy targets, where applicable, and can take on one or more of the following values: & All Mechansims (except visa restrictions), Flights, Land Border, Trains, Buses, Seaports, Ferries, Cruises, Visas\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

There is a unique \texttt{record\_id} for the following unit of analysis: \texttt{country} - \texttt{date\_announced} - \texttt{type}.\footnote{Note, this is the unit of analysis provided in the wide version of our dataset. The long verision of the dataset, labeled as file name: XXX, is organized by \texttt{country} - \texttt{target\_country}- \texttt{date\_announced} - \texttt{type}.} Of the 6782 such events in the dataset, we have identified 5777 unique events. That is, some events in the database are updates or changes to existing policies. We link such events overtime using a unique ID (\texttt{policy\_id}). An event counts as an update if it deals with a change in either the:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Time duration or\footnote{E.g. A country lengthens its quarantine to 28 days from 14 days.}
\item
  Strength of an existing policy in terms of either:

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \tightlist
  \item
    the nature of the policy\footnote{E.g. People can no longer leave their houses to go to work whereas before they could}
  \item
    compliance rules for the policy\footnote{E.g The quarantine used to be voluntary but now its mandatory}
  \item
    who the policy applies towards\footnote{E.g. The quarantine used to apply to people of all ages and now it only applies to the elderly.}
  \end{enumerate}
\end{enumerate}

A policy counts as a new entry and not an update if it deals with a change in any other dimension, e.g.~policy type, targeted country. Table \ref{tab:desctab} shows the number of records for each policy type, the number of unique countries for each policy type, and also how many countries are targeted in total by each policy type. We note that these are cumulative totals for these different categories in the data.

\begin{table}[!h]

\caption{\label{tab:desctab}Descriptive Information about the CoronaNet Government Response Dataset}
\centering
\begin{tabular}{>{\raggedright\arraybackslash}p{4cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}}
\toprule
Type & Total Number of Policies & Number of Countries & Number of Targeted Countries & \% With Mandatory Enforcement\\
\midrule
\rowcolor{gray!6}  Closure of Schools & 1250 & 157 & 3 & 86\\
Curfew & 175 & 87 & 21 & 97\\
\rowcolor{gray!6}  Declaration of Emergency & 318 & 109 & 1 & 82\\
External Border Restrictions & 4061 & 178 & 201 & 90\\
\rowcolor{gray!6}  Health Monitoring & 607 & 99 & 198 & 75\\
\addlinespace
Health Resources & 1342 & 128 & 125 & 54\\
\rowcolor{gray!6}  Health Testing & 251 & 76 & 100 & 78\\
Internal Border Restrictions & 255 & 104 & 94 & 87\\
\rowcolor{gray!6}  New Task Force or Bureau & 218 & 90 & 1 & 49\\
Other Policy Not Listed Above & 556 & 119 & 1 & 61\\
\addlinespace
\rowcolor{gray!6}  Public Awareness Campaigns & 394 & 115 & 1 & 24\\
Quarantine/Lockdown & 2841 & 145 & 202 & 80\\
\rowcolor{gray!6}  Restriction of Non-Essential Businesses & 1241 & 125 & 1 & 92\\
Restriction of Non-Essential Government Services & 206 & 84 & 1 & 83\\
\rowcolor{gray!6}  Restrictions of Mass Gatherings & 521 & 148 & 2 & 86\\
\addlinespace
Social Distancing & 382 & 113 & 2 & 72\\
\bottomrule
\end{tabular}
\end{table}

In addition, we can look at the cumulative incidence of different types of policies in our data over time, as we show in Figure \ref{fig:overtime}. The figure shows that relatively easy to implement policies like the forming of task forces, public awareness campaigns, and efforts to increase health resources came relatively early. More restrictive policies like curfews, closures of schools and mass gatherings arrived later in the course of the pandemic.

\begin{figure}
\centering
\includegraphics{corona_wp_files/figure-latex/overtime-1.pdf}
\caption{\label{fig:overtime}Cumulative Incidence of Policy Event Types Over Time}
\end{figure}

We can also explore the extent to which other countries are affected by policies that can have a geographic target outside the policy initiator (e.g.~`external border restrictions', `quarantine'). For example, in Figure @ref(fig:biofabric\_europe), we map a network of bans on inbound flights to European countries initiated by European countries\footnote{In this paper, the following countries are defined as being in Europe: Albania, Andorra, Armenia, Austria, Belarus, Belgium, Bosnia and Herzegovina, Bulgaria, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Georgia, Germany, Greece, Hungary, Iceland, Ireland, Italy, Kosovo, Latvia, Liechtenstein, Lithuania, Luxembourg, Macedonia, Malta, Moldova, Monaco, Montenegro, Netherlands, Norway, Poland, Portugal, Romania, San Marino, Serbia, Slovakia, Slovenia, Spain, Sweden, Switzerland, Ukraine, United Kingdom, and the Vatican} as of March 15, 2020. In the plot, each horizontal line represents a potential geographical target of a flight ban. The vertical lines denote whether there was such a flight ban and the arrow of the vertical line indicates the direction in which the ban is applied.\footnote{(See Longabaugh 2012 for more information on how to interpret this plot.)} The figure shows that by March 15, 2020, the governments of Poland and San Marino had banned all flights into Poland and San Marino respectively while the government of the autonomous region of Madeira, Portugal had banned flights from Denmark, Finland, France, Germany, Spain, and Switzerland. Meanwhile, according to our data, no other countries in Europe had banned inbound flights from other countries.

\begin{figure}
\centering
\includegraphics{corona_wp_files/figure-latex/biofabric_europe-1.pdf}
\caption{(\#fig:biofabric\_europe)Network Map of Bans on Inbound Flights by European Countries as of March 15, 2020}
\end{figure}

\hypertarget{government-policy-activity-index}{%
\section{Government Policy Activity Index}\label{government-policy-activity-index}}

In this section we briefly present our new index for tracking how relatively active governments are in addressing COVID-19 across countries and over time. The model is a version of item-response theory that incorporates over-time trends (Kubinec 2019), permitting inference on how a latent construct, in this case policy stringency, is responding to changes in the pandemic. To fit the model, the different policy types shown in Table \ref{tab:desctab} were coded dichotomously, with a value of 1 if enforcement of the policy was mandatory, and 0 otherwise. As a result, the model estimates whether mandatory policies for each category exist for each country on each day. The country-level stringency score is allowed to vary over time in a random-walk process with a country-specific variance parameter (i.e., to incorporate heteroskedasticity).

The advantage of employing a statistical model, rather than simply summing across policies, is that the index ends up as a weighted average, where the weights are derived from the probability that a certain policy is enforced. In other words, while many countries set up task forces, relatively few imposed curfews at an early stage. As a result, the model adjusts for these distinctions, producing a score that aggregates across the patterns in the data. Because over-time trends are explicitly included and jointly estimated with the latent parameters, the model will implicitly up-weight countries that took harsher measures earlier.

Furthermore, because the model is stochastic, it is robust to coding errors of the kind that often occur in these types of datasets. As we discuss in our validation section, while we are continuing to validate the data on a daily basis, the massive speed and scope of data collection means that we cannot identify all issues with the data in real time. However, the measurement model employed only requires us to assume that on average the policy codings are correct, not that they are correct for each instance. Coding error, such as incorrectly selecting a policy type, will propagate through the model as higher uncertainty intervals, but will not affect average posterior estimates. As our data quality improves, and we are able to collect more data over time, the model will produce more variegated estimates with smaller uncertainty intervals.

Figure \ref{fig:plotindex} shows the estimated index scores for the 0 countries in our dataset at present. Of course, a caveat with the index is that we may be missing some possible policy measures that have occurred due to the difficulty in finding them in published sources. However, there is still clear differentiation within the index in terms of when policies were imposed, with some countries starting to impose policies much earlier than others. Furthermore, there is a clear break about March 1st when countries began to impose more stringent policies across the world.

Figure \ref{fig:plotindex} shows the estimated index scores for the 0 countries in our dataset at present. Of course, a caveat with the index is that we may be missing some possible policy measures that have occurred due to the difficulty in finding them in published sources. However, there is still clear differentiation within the index in terms of when policies were imposed, with some countries starting to impose policies much earlier than others. Furthermore, there is a clear break about March 1st when countries began to impose more stringent policies across the world.

\begin{figure}
\centering
\includegraphics{corona_wp_files/figure-latex/plotindex-1.pdf}
\caption{\label{fig:plotindex}CoronaNet Time-Varying Index of National Policy Activity of Measures Opposing COVID-19 Pandemic}
\end{figure}

Table \ref{tab:rankcount} shows the rank of countries for the index at present. An important note about these results is that the rank only measures the posterior median, or most likely estimate, but the 5\% - 95\% uncertainty interval shows that substantial uncertainty exists in comparing neighboring countries in the index. More certain comparisons can be made between the top, middle and bottom third of countries, while within these categories the estimates are not precise enough to make finer-grained distinctions with confidence.

With this caveat in mind, San Marino occupies the highest position, likely because of harsh lockdowns imposed as a result of the outbreak in northern Italy that occurred relatively early. Slovenia has had a nationwide lockdown in place for several weeks, while Azerbaijan took early action to close its borders with Iran in February after the outbreak started. It is important to note the uncertainty in the index measures, as the top 10 countries cannot be distinguished from each other in severity except for San Marino. We believe these uncertainty intervals are important to capture the difficulty in using published policies to compare countries. However, we also see substantial value in this index, particularly in its ability to show change over time.

\begin{longtable}{>{\raggedright\arraybackslash}p{4cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}}
\caption{\label{tab:rankcount}Rank of Countries by National Policy Activity Index as of April 3rd, 2020}\\
\toprule
Country & Rank & 5\% Low Score & Median Score & 95\% High Score\\
\midrule
\rowcolor{gray!6}  Gabon & 1 & 61.3 & 63.6 & 66.4\\
Croatia & 2 & 59.3 & 62.8 & 66.1\\
\rowcolor{gray!6}  United Arab Emirates & 3 & 58.6 & 62.4 & 66.9\\
Guatemala & 4 & 58.8 & 61.8 & 65.0\\
\rowcolor{gray!6}  Slovenia & 5 & 58.2 & 61.5 & 64.7\\
\addlinespace
San Marino & 6 & 57.2 & 61.5 & 66.0\\
\rowcolor{gray!6}  Eswatini & 7 & 57.1 & 61.3 & 65.6\\
Antigua and Barbuda & 8 & 58.0 & 61.2 & 64.1\\
\rowcolor{gray!6}  Hungary & 9 & 58.2 & 61.2 & 65.2\\
Poland & 10 & 56.5 & 61.1 & 66.3\\
\addlinespace
\rowcolor{gray!6}  Latvia & 11 & 59.5 & 61.1 & 62.8\\
Grenada & 12 & 55.8 & 61.1 & 66.4\\
\rowcolor{gray!6}  Iraq & 13 & 58.4 & 60.9 & 63.6\\
Mali & 14 & 59.2 & 60.9 & 63.1\\
\rowcolor{gray!6}  Albania & 15 & 57.8 & 60.7 & 63.8\\
\addlinespace
Romania & 16 & 58.0 & 60.7 & 63.4\\
\rowcolor{gray!6}  Israel & 17 & 58.8 & 60.7 & 62.5\\
Saudi Arabia & 18 & 57.3 & 60.7 & 64.1\\
\rowcolor{gray!6}  Peru & 19 & 59.2 & 60.6 & 62.3\\
Democratic Republic of the Congo & 20 & 58.2 & 60.6 & 63.0\\
\addlinespace
\rowcolor{gray!6}  Costa Rica & 21 & 59.8 & 60.6 & 61.7\\
Botswana & 22 & 57.0 & 60.5 & 64.4\\
\rowcolor{gray!6}  Bulgaria & 23 & 58.3 & 60.5 & 62.6\\
Saint Kitts and Nevis & 24 & 57.9 & 60.5 & 62.8\\
\rowcolor{gray!6}  Netherlands & 25 & 55.5 & 60.5 & 65.8\\
\addlinespace
Madagascar & 26 & 57.6 & 60.4 & 63.0\\
\rowcolor{gray!6}  Austria & 27 & 60.0 & 60.3 & 60.9\\
Belgium & 28 & 58.5 & 60.2 & 62.7\\
\rowcolor{gray!6}  Russia & 29 & 58.5 & 60.2 & 62.0\\
Kuwait & 30 & 59.7 & 60.2 & 61.0\\
\addlinespace
\rowcolor{gray!6}  Switzerland & 31 & 57.4 & 60.1 & 62.4\\
Ukraine & 32 & 56.9 & 60.1 & 63.6\\
\rowcolor{gray!6}  Malta & 33 & 53.3 & 60.1 & 67.0\\
Lesotho & 34 & 56.2 & 60.1 & 63.7\\
\rowcolor{gray!6}  Cyprus & 35 & 58.7 & 60.1 & 61.5\\
\addlinespace
Uruguay & 36 & 51.8 & 60.0 & 67.6\\
\rowcolor{gray!6}  Angola & 37 & 57.2 & 60.0 & 62.7\\
Djibouti & 38 & 51.3 & 60.0 & 71.0\\
\rowcolor{gray!6}  Monaco & 39 & 57.6 & 60.0 & 62.6\\
Luxembourg & 40 & 55.0 & 59.9 & 64.9\\
\addlinespace
\rowcolor{gray!6}  Finland & 41 & 58.9 & 59.9 & 61.0\\
Spain & 42 & 58.6 & 59.9 & 61.0\\
\rowcolor{gray!6}  Uganda & 43 & 56.5 & 59.9 & 63.6\\
Italy & 44 & 57.6 & 59.9 & 62.3\\
\rowcolor{gray!6}  Eritrea & 45 & 56.4 & 59.9 & 63.3\\
\addlinespace
Chile & 46 & 56.7 & 59.8 & 63.0\\
\rowcolor{gray!6}  Colombia & 47 & 59.0 & 59.8 & 60.5\\
Kenya & 48 & 58.9 & 59.7 & 60.6\\
\rowcolor{gray!6}  Jordan & 49 & 47.1 & 59.7 & 70.8\\
Denmark & 50 & 53.2 & 59.7 & 66.5\\
\addlinespace
\rowcolor{gray!6}  Ireland & 51 & 58.2 & 59.7 & 61.1\\
North Macedonia & 52 & 59.3 & 59.7 & 60.1\\
\rowcolor{gray!6}  United Kingdom & 53 & 55.5 & 59.7 & 64.3\\
Kazakhstan & 54 & 57.5 & 59.7 & 61.9\\
\rowcolor{gray!6}  Gambia & 55 & 59.1 & 59.7 & 60.4\\
\addlinespace
Azerbaijan & 56 & 59.5 & 59.7 & 59.9\\
\rowcolor{gray!6}  Morocco & 57 & 57.7 & 59.7 & 61.7\\
Moldova & 58 & 55.4 & 59.6 & 63.3\\
\rowcolor{gray!6}  Qatar & 59 & 57.2 & 59.6 & 62.4\\
South Africa & 60 & 58.6 & 59.6 & 60.7\\
\addlinespace
\rowcolor{gray!6}  Jamaica & 61 & 58.8 & 59.6 & 60.4\\
Mauritania & 62 & 56.7 & 59.6 & 63.0\\
\rowcolor{gray!6}  Hong Kong & 63 & 59.0 & 59.6 & 60.1\\
Lithuania & 64 & 58.9 & 59.6 & 60.4\\
\rowcolor{gray!6}  Tonga & 65 & 53.7 & 59.5 & 64.9\\
\addlinespace
Germany & 66 & 53.9 & 59.5 & 65.1\\
\rowcolor{gray!6}  Samoa & 67 & 59.1 & 59.5 & 60.0\\
Ivory Coast & 68 & 57.2 & 59.5 & 61.8\\
\rowcolor{gray!6}  Portugal & 69 & 59.2 & 59.5 & 59.8\\
Ethiopia & 70 & 57.7 & 59.5 & 60.9\\
\addlinespace
\rowcolor{gray!6}  Niger & 71 & 56.8 & 59.5 & 61.9\\
Slovakia & 72 & 56.8 & 59.5 & 62.4\\
\rowcolor{gray!6}  China & 73 & 58.1 & 59.5 & 60.9\\
Liechtenstein & 74 & 57.6 & 59.5 & 61.6\\
\rowcolor{gray!6}  Ecuador & 75 & 57.1 & 59.5 & 61.9\\
\addlinespace
Cameroon & 76 & 55.3 & 59.4 & 63.2\\
\rowcolor{gray!6}  Kyrgyzstan & 77 & 58.1 & 59.4 & 60.7\\
Dominica & 78 & 58.3 & 59.4 & 60.8\\
\rowcolor{gray!6}  El Salvador & 79 & 56.9 & 59.4 & 62.1\\
Cambodia & 80 & 57.8 & 59.4 & 61.0\\
\addlinespace
\rowcolor{gray!6}  Bolivia & 81 & 52.9 & 59.4 & 65.2\\
Mexico & 82 & 57.6 & 59.4 & 61.0\\
\rowcolor{gray!6}  Sudan & 83 & 55.8 & 59.4 & 62.9\\
Turkey & 84 & 57.8 & 59.3 & 61.2\\
\rowcolor{gray!6}  Somalia & 85 & 56.3 & 59.3 & 62.5\\
\addlinespace
Togo & 86 & 57.7 & 59.3 & 61.1\\
\rowcolor{gray!6}  Honduras & 87 & 59.0 & 59.3 & 59.6\\
Iran & 88 & 59.0 & 59.3 & 59.7\\
\rowcolor{gray!6}  Mongolia & 89 & 58.6 & 59.3 & 60.0\\
Serbia & 90 & 52.6 & 59.3 & 66.3\\
\addlinespace
\rowcolor{gray!6}  Paraguay & 91 & 58.5 & 59.3 & 59.9\\
Australia & 92 & 53.6 & 59.3 & 64.9\\
\rowcolor{gray!6}  Burkina Faso & 93 & 58.4 & 59.3 & 60.1\\
Tanzania & 94 & 58.4 & 59.3 & 60.2\\
\rowcolor{gray!6}  Egypt & 95 & 58.9 & 59.3 & 59.6\\
\addlinespace
Bhutan & 96 & 57.6 & 59.2 & 60.9\\
\rowcolor{gray!6}  Palestine & 97 & 58.2 & 59.2 & 60.2\\
France & 98 & 57.6 & 59.2 & 60.9\\
\rowcolor{gray!6}  Pakistan & 99 & 58.7 & 59.2 & 59.7\\
Benin & 100 & 55.4 & 59.2 & 62.8\\
\addlinespace
\rowcolor{gray!6}  Brazil & 101 & 48.5 & 59.2 & 71.0\\
Papua New Guinea & 102 & 57.4 & 59.2 & 61.1\\
\rowcolor{gray!6}  Algeria & 103 & 57.5 & 59.2 & 61.0\\
Mozambique & 104 & 58.9 & 59.2 & 59.5\\
\rowcolor{gray!6}  Philippines & 105 & 51.4 & 59.2 & 67.5\\
\addlinespace
Senegal & 106 & 56.6 & 59.2 & 62.4\\
\rowcolor{gray!6}  Estonia & 107 & 55.2 & 59.2 & 63.9\\
Oman & 108 & 58.7 & 59.2 & 59.6\\
\rowcolor{gray!6}  Cuba & 109 & 56.6 & 59.2 & 61.7\\
Suriname & 110 & 58.7 & 59.2 & 59.7\\
\addlinespace
\rowcolor{gray!6}  Tunisia & 111 & 57.5 & 59.2 & 61.0\\
Argentina & 112 & 57.2 & 59.1 & 61.1\\
\rowcolor{gray!6}  Taiwan & 113 & 58.6 & 59.1 & 59.7\\
Sierra Leone & 114 & 55.5 & 59.1 & 62.5\\
\rowcolor{gray!6}  Thailand & 115 & 55.8 & 59.1 & 62.3\\
\addlinespace
Equatorial Guinea & 116 & 56.6 & 59.1 & 61.9\\
\rowcolor{gray!6}  Rwanda & 117 & 56.1 & 59.1 & 62.9\\
Kiribati & 118 & 51.6 & 59.1 & 66.7\\
\rowcolor{gray!6}  Trinidad and Tobago & 119 & 56.4 & 59.1 & 61.8\\
Guyana & 120 & 55.9 & 59.1 & 62.7\\
\addlinespace
\rowcolor{gray!6}  Vanuatu & 121 & 58.2 & 59.1 & 59.9\\
Namibia & 122 & 53.8 & 59.1 & 64.8\\
\rowcolor{gray!6}  Solomon Islands & 123 & 56.9 & 59.1 & 62.1\\
Republic of the Congo & 124 & 57.5 & 59.0 & 60.6\\
\rowcolor{gray!6}  Saint Vincent and the Grenadines & 125 & 57.9 & 59.0 & 60.4\\
\addlinespace
Sao Tome and Principe & 126 & 56.9 & 59.0 & 61.2\\
\rowcolor{gray!6}  Brunei & 127 & 54.5 & 59.0 & 63.7\\
Bahamas & 128 & 53.6 & 59.0 & 64.4\\
\rowcolor{gray!6}  South Sudan & 129 & 53.9 & 59.0 & 64.1\\
Zambia & 130 & 53.8 & 59.0 & 64.9\\
\addlinespace
\rowcolor{gray!6}  Iceland & 131 & 58.5 & 59.0 & 59.4\\
Panama & 132 & 58.0 & 59.0 & 60.0\\
\rowcolor{gray!6}  Sri Lanka & 133 & 55.0 & 58.8 & 62.7\\
Sweden & 134 & 55.9 & 58.8 & 61.2\\
\rowcolor{gray!6}  Belarus & 135 & 57.7 & 58.8 & 60.1\\
\addlinespace
Burundi & 136 & 54.3 & 58.8 & 62.6\\
\rowcolor{gray!6}  Myanmar & 137 & 58.0 & 58.7 & 59.5\\
Central African Republic & 138 & 56.3 & 58.6 & 61.7\\
\rowcolor{gray!6}  Guinea & 139 & 54.5 & 58.5 & 61.9\\
Uzbekistan & 140 & 53.2 & 58.5 & 64.6\\
\addlinespace
\rowcolor{gray!6}  Barbados & 141 & 57.3 & 58.5 & 59.7\\
Malawi & 142 & 52.5 & 58.4 & 63.3\\
\rowcolor{gray!6}  Indonesia & 143 & 57.5 & 58.3 & 59.0\\
Turkmenistan & 144 & 54.6 & 58.3 & 62.9\\
\rowcolor{gray!6}  Czechia & 145 & 57.6 & 58.2 & 59.0\\
\addlinespace
Ghana & 146 & 55.9 & 58.2 & 61.2\\
\rowcolor{gray!6}  Dominican Republic & 147 & 56.7 & 58.1 & 60.1\\
Japan & 148 & 57.5 & 58.1 & 58.7\\
\rowcolor{gray!6}  Georgia & 149 & 54.5 & 58.1 & 61.6\\
Timor Leste & 150 & 54.7 & 58.1 & 61.7\\
\addlinespace
\rowcolor{gray!6}  Lebanon & 151 & 56.1 & 58.0 & 60.5\\
Fiji & 152 & 54.8 & 57.9 & 61.4\\
\rowcolor{gray!6}  Vietnam & 153 & 54.2 & 57.8 & 61.0\\
Nepal & 154 & 56.8 & 57.7 & 58.5\\
\rowcolor{gray!6}  Libya & 155 & 54.0 & 57.7 & 63.5\\
\addlinespace
Singapore & 156 & 52.8 & 57.6 & 62.0\\
\rowcolor{gray!6}  Norway & 157 & 54.9 & 57.6 & 60.3\\
Canada & 158 & 52.9 & 57.6 & 63.4\\
\rowcolor{gray!6}  Maldives & 159 & 52.1 & 57.6 & 62.6\\
Tajikistan & 160 & 50.4 & 57.5 & 63.5\\
\addlinespace
\rowcolor{gray!6}  Zimbabwe & 161 & 52.8 & 57.5 & 61.8\\
Venezuela & 162 & 52.9 & 57.5 & 61.7\\
\rowcolor{gray!6}  Nigeria & 163 & 54.3 & 57.5 & 60.4\\
Montenegro & 164 & 53.4 & 57.4 & 60.5\\
\rowcolor{gray!6}  Andorra & 165 & 54.6 & 57.4 & 60.1\\
\addlinespace
New Zealand & 166 & 50.3 & 57.3 & 63.3\\
\rowcolor{gray!6}  United States & 167 & 56.3 & 57.3 & 58.1\\
Afghanistan & 168 & 54.0 & 57.3 & 61.2\\
\rowcolor{gray!6}  Comoros & 169 & 51.8 & 57.3 & 62.6\\
Syria & 170 & 53.3 & 57.3 & 60.4\\
\addlinespace
\rowcolor{gray!6}  Bangladesh & 171 & 55.1 & 57.0 & 59.4\\
South Korea & 172 & 51.8 & 56.5 & 60.4\\
\rowcolor{gray!6}  Seychelles & 173 & 52.4 & 56.4 & 63.1\\
Bosnia and Herzegovina & 174 & 48.1 & 56.3 & 61.9\\
\rowcolor{gray!6}  Micronesia & 175 & 45.5 & 56.3 & 67.6\\
\addlinespace
Nauru & 176 & 49.8 & 56.3 & 61.3\\
\rowcolor{gray!6}  Liberia & 177 & 48.4 & 56.1 & 61.4\\
North Korea & 178 & 48.5 & 56.0 & 62.4\\
\rowcolor{gray!6}  Tuvalu & 179 & 48.4 & 55.9 & 61.5\\
Armenia & 180 & 50.7 & 55.8 & 59.9\\
\addlinespace
\rowcolor{gray!6}  Cabo Verde & 182 & 48.3 & 55.3 & 60.0\\
India & 183 & 45.0 & 54.0 & 59.5\\
\rowcolor{gray!6}  Macau & 184 & 40.8 & 52.3 & 58.4\\
Saint Lucia & 185 & 36.6 & 51.1 & 59.4\\
\rowcolor{gray!6}  Yemen & 186 & 34.3 & 48.9 & 56.4\\
\bottomrule
\end{longtable}

Finally, we note in Figure \ref{fig:plotindex} the strong evidence of policy diffusion effects. While information about COVID-19 existed at least as early as January, we do not see large-scale changes occurring in severity scores until March. Furthermore, the trajectories are highly non-linear, with a large number of countries quickly transitioning from relatively low to relatively high scores. This tandem movement is a strong indication of policy diffusion as countries adopted similar policies across time and space as opposed to a more linear learning process.
=======
In what follows, we describe in greater detail the methodology we employed to collect this data, a description of the data, and also the application of our data in modeling the stringency of measures over time. Using a Bayesian dynamic item-response theory model, we produce a statistically-valid index that ranks countries in terms of their reponse to the pandemic, and also shows how quickly policy responses have changed over time. For more information on the exact variables collected, please see our publicly available codebook \href{https://docs.google.com/document/d/1zvNMpwj0onFvUZ_gLl4RRjqS-clbHv3TIX6EOHofsME/edit?usp=sharing}{at this link}.
>>>>>>> d7438a47fcf5fa95add9dbd70877c58facbca097

\hypertarget{methodology}{%
\section{Methodology}\label{methodology}}

<<<<<<< HEAD
To collect the data, we recruited more than 190 research assistants (RAs) from colleges and universities around the world, representing 18 out of the 24 time zones.\footnote{For more information on the individual RAs, please visit \url{http://coronanet-project.org/}} Data collection started on March 28, 2020 and has proceeded very rapidly, reaching 6782 records as of the date of this article. Each RA is responsible for tracking government policy actions for at least one country. RAs were allocated depending on their background, language skills and expressed interest in certain countries.\footnote{Note depending on the level of policy coordination at the national level, certain countries were assigned multiple RAs, e.g.~the United States, Germany, or France.}
=======
<<<<<<< HEAD
The collection of the dataset was done by XXX research assistants (RAs)\footnote{For more information on the individual RAs, please visit \url{http://coronanet-project.org/people} } from March 28, 2020 up to date without whom this dataset would not exist, and who are still making ongoing efforts to collecting real-time data on government COVID-19 policy actions. Each RA is responsible for tracking government policy actions for at least one country. RAs were allocated depending on their background, language skills and expressed interest in certain countries.\footnote{Note depending on the level of policy coordination at the national level, certain countries were assigned multiple RAs, e.g.~the United States, Germany, or France. For a comprehensive list of which RAs were assigned to which country, please see the Appendix.}
=======
To collect the data, we recruited 178 research assistants (RAs) from colleges and universities around the world, representing 18 out of the 24 time zones.\footnote{For more information on the individual RAs, please visit \url{http://coronanet-project.org/people}} Data collection started on March 28, 2020 and has proceeded very rapidly, accumulating 4695 records as of the date of this article. Each RA is responsible for tracking government policy actions for at least one country. RAs were allocated depending on their background, language skills and expressed interest in certain countries.\footnote{Note depending on the level of policy coordination at the national level, certain countries were assigned multiple RAs, e.g.~the United States, Germany, or France. For a comprehensive list of which RAs were assigned to which country, please see the Appendix.}
>>>>>>> d7438a47fcf5fa95add9dbd70877c58facbca097

We have also partnered with the machine learning company Jataware to automate the collection of more than 200,000 news articles from around the world related to COVID-19.\footnote{We thank Brandon Rose and Jataware for making the news database available to this project.} Jataware employes a natural language processing (NLP) classifier using Bidirectional Encoder Representations from Transformers (BERT) to detect whether a given article is indicative of a governmental policy intervention related to COVID-19. They then apply a secondary NLP classifier to categorize the type of policy intervention (e.g.~``state of emergency'', ``shelter-in-place'', ``quarantine'', ``travel restrictions'', etc). Next, Jataware extracts the geospatial and temporal extent of the policy intervention (e.g.~``Washington DC'' and ``March 15, 2020'') whenever possible. The resulting list of news sources is then provided to our RAs for manual coding and further data validation.
>>>>>>> 8abfe42c67c9454dad613caa0e6e9ac7157a85e8

As researchers learn more about the various health, economic, and social effects of the corona-virus pandemic, it is crucial that they have access to both reliable, valid, and timely data. We have adopted the following data collection methodology to ensure the availability of such data as rapidly as possible while still maintaining high standards of quality at every stage of the data collection process.

\hypertarget{data-collection-software-instrument}{%
\subsection{Data Collection Software Instrument}\label{data-collection-software-instrument}}

To streamline the CoronaNet data collection effort, we designed a Qualtrics survey with survey questions about different aspects of a government policy action. With this tool, RAs can easily and efficiently document different policy actions by answering the relevant questions posed in the survey. For example, instead of entering the country that initiated a policy action into a spreadsheet, RAs answer the following question in the survey: ``From what country does this policy originate from?'' and choose from the available options given in the survey.

<<<<<<< HEAD
By using a survey instrument to collect data, we are able to systemetize the collection of very fine-grained data. The value of this approach of course, depends on the comprehensiveness of the questions posed in the survey, especially in terms of the universe of policy actions that countries have implemented against COVID-19. For example, if the survey only allowed RAs to select `qurantines' as a government policy, it would not capture any data on external border restrictions, which would seriously reduce the value of the resulting data.

As such, to ensure the comprehensiveness of the data, before designing the survey, one of the PIs collected in depth, over-time data on policy actions taken by one country, Taiwan, since the beginning of the outbreak as well as cross-national data on travel bans implemented by most countries for a total of more than 450 events.\footnote{The specific data source the PI cross referenced for this effort was the March 20, 2020 version of the following New York Times article Salcedo, Andrea and Gina Cherelus, ``Coronavirus Travel Restrictions, Across the Globe'' \emph{New York Times}, 20 March 2020, \url{https://www.nytimes.com/article/coronavirus-travel-restrictions.html}} We chose to focus on Taiwan on because of its relative success, as of March 28, 2020, in limiting the negative health consequences of the coronavirus within its borders.\footnote{Beech, Hannah. ``Tracking the Coronavirus: How Crowded Asian Cities Tackled an Epidemic.'' \emph{New York Times} 18 March 2020 \url{https://www.nytimes.com/2020/03/17/world/asia/coronavirus-singapore-hong-kong-taiwan.html}} As such, it seems likely that other countries may choose to emulate some of the policy measures that Taiwan had implemented, which helps increase the comprehensiveness of the questions we ask in our survey. Meanwhile, by also investigating variation in how different countries around the world have implemented travel restrictions, we have also helped ensure that our survey is able to comprehensively document variation in how an important and commonly used policy tool is applied, e.g.~restrictions of different methods of travel (e.g.~flights, cruises), restrictions across borders and within borders, restrictions targeted toward people of different status (e.g.~citizens, travelers).

Using machine learning and web automation, the corporation Jataware has collected over 200,000 news articles from around the world related to COVID-19 as part of its ongoing effort to understand governmental responses to the pandemic \footnote{We thank Brandon Rose and Jataware for making the news database available to this project.}. On basis of this source we have developed a natural language processing (NLP) classifier using Bidirectional Encoder Representations from Transformers (BERT) to detect whether a given article is indicative of a governmental policy intervention related to COVID-19. We then apply a secondary NLP classifier to categorize the type of policy intervention (e.g.~``state of emergency'', ``shelter-in-place'', ``quarantine'', ``travel restrictions'', etc). Next, we extract the geospatial and temporal extent of the policy intervention (e.g.~``Washington DC'' and ``March 15, 2020'') whenever possible. Through this approach, we are continuously adding to our high-recall dataset, which can be further refined through human annotation or additional machine learning and AI.

As a last step, the team also consulted the ACAPS COVID-19: Government Measures Dataset\footnote{\url{https://data.humdata.org/dataset/acaps-covid19-government-measures-dataset}} to validate the comprehensiveness of the policy measures considered in the survey instrument.
=======
By using a survey instrument to collect data, we are able to systemetize the collection of very fine-grained data while avoiding coding errors common to tools like shared spreadsheets. The value of this approach of course, depends on the comprehensiveness of the questions posed in the survey, especially in terms of the universe of policy actions that countries have implemented against COVID-19. For example, if the survey only allowed RAs to select `quarantines' as a government policy, it would not capture any data on external border restrictions, which would seriously reduce the value of the resulting data.
>>>>>>> 8abfe42c67c9454dad613caa0e6e9ac7157a85e8

As such, to ensure the comprehensiveness of the data, before designing the survey, one of the authors collected in depth, over-time data on policy actions taken by one country, Taiwan, since the beginning of the outbreak as well as cross-national data on travel bans implemented by most countries for a total of 245 events.\footnote{The specific data source the PI cross referenced for this effort was the March 20, 2020 version of the following New York Times article Salcedo, Andrea and Gina Cherelus, ``Coronavirus Travel Restrictions, Across the Globe'' \emph{New York Times}, 20 March 2020, \url{https://www.nytimes.com/article/coronavirus-travel-restrictions.html}} We chose to focus on Taiwan on because of its relative success, as of March 28, 2020, in limiting the negative health consequences of the coronavirus within its borders.\footnote{Beech, Hannah. ``Tracking the Coronavirus: How Crowded Asian Cities Tackled an Epidemic.'' \emph{New York Times} 18 March 2020 \url{https://www.nytimes.com/2020/03/17/world/asia/coronavirus-singapore-hong-kong-taiwan.html}} As such, it seems likely that other countries may choose to emulate some of the policy measures that Taiwan had implemented, which helps increase the comprehensiveness of the questions we ask in our survey. Meanwhile, by also investigating variation in how different countries around the world have implemented travel restrictions, we have also helped ensure that our survey is able to comprehensively document variation in how an important and commonly used policy tool is applied, e.g.~restrictions of different methods of travel (e.g.~flights, cruises), restrictions across borders and within borders, restrictions targeted toward people of different status (e.g.~citizens, travelers).

There are many additional benefits of using a survey instrument for data collection, especially in terms of ensuring the reliability and validity of the resulting the data:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  First, we reduce the likelihood of unforced measurement error. Because RAs can only document one policy action at a time in a given iteration of a survey and do not have access to the full spreadsheet when they are entering in the data, they are prevented from entering data into incorrect fields or unknowingly overwriting existing data, as would be possible with manual data entry into a spreadsheet.
\item
  For another, we are able to ensure that RAs can only choose among standardized responses to the survey questions, which increases the reliability of the data and also reduces the likelihood of measurement error. For example, when RAs choose different dates that we would like them to document (e.g., the date a policy was announced) they are forced to choose from a calendar embedded into the survey which systemizes the day, month and year format that the date is recorded in.
\item
  Moreover, we also reduce measurement error by coding in different conditional logics for when certain survey questions are posed, which obviates the occurence of logical fallacies in our data. For example, we are able to avoid a situations where an RA might accidentally code the United States as having closed all schools in another country.
\item
  Meanwhile, by using the forced response option in Qualtrics, we are also able to reduce the amount of missing data in the dataset. Where there is truly missing data due, there is a text entry at the end of the survey where RAs can describe what difficulties they encountered in collecting information for a particular policy event.
\item
  We also increase the reliability of the documentation for each policy by embedding descriptions of different possible responses within the survey. For example, in the survey question where RAs are asked to identify the policy type (`type' variable, see Codebook), the survey question includes pop-up buttons which allow RAs to easily get descriptions and examples of each possible policy type. Such pop-up buttons were also made availble for the survey questions which code for the people or materials a policy was targed at (`target\_who\_what') and whether the policy was inbound, outbound or both (`target\_direction'). Embedding such information in the dataset both clarifies the distinction between different answer choices and increases the efficiency of the policy documentation process (as RAs are not obliged to refer back and forth from the survey to the codebook).
\item
  Finally, the use of a survey instrument allows us to easily link policy events together over time should there be updates to existing policies. Once coded, each policy is given a unique Record ID, which RAs can easily look up, reference and link to if they need to update a particular policy.
\end{enumerate}

\hypertarget{ra-training}{%
\subsection{RA Training}\label{ra-training}}

All RAs watch a mandatory 50 minute video training of the survey instrument which explains how to use the survey instrument. RAs are also provided with written guidelines on how to collect data and a comprehensive codebook. While both of these documents are availble in the Appendix, to briefly describe it here, the written guidelines provide a definition of what counts as a new or updated policy and provides a checklist for RAs to follow in order to identify and document different policies. In the checklist, RAs are instructed to check the data sources in the order given in the guidelines to identify policies, to document the relevant information into the survey and to save and upload a .pdf of the source they found to document each policy into Qualtrics. The codebook meanwhile provides provides descriptions and examples of the different possible response options in the survey. Using a training video and the written codebook also has the added benefit of helping us efficiently disseminate the information RAs need to use the survey experiment consistently.

In order to participate as an RA in this project, RAs must fill out the CoronaNet Research Assistant Form\footnote{\url{https://docs.google.com/forms/d/e/1FAIpQLSeybAW0DC0UE1x2EqLiTifVFuSUxqJLGFB8VI4wVCG61tVYKg/viewform}} in which:

\begin{itemize}
\tightlist
\item
  They identify themselves.
\item
  They certify that they have viewed the training video in which we explain how to use the survey instrument.
\item
  They certify they have joined the CoronaNet Slack Channel (see section below for more information).
\item
  They certify that they understand that RA responsibilities entail
\item
  gathering historical data on COVID-19 government policy actions for my country, and;
\item
  providing daily updates for new government policy actions.
\item
  They certify that they understand they can access the data collection guidlines and codebook or pose their questions on the Slack Channel should they have any questions.
\item
  They certify that they are expected to upload .pdfs of the sources they access to the survey instrument.
\end{itemize}

Once the RA submits the form, they are sent a personalized link to access the survey. With the customized link, we are also able to keep track of which RA coded what entries.

\hypertarget{real-time-communication-and-feedback}{%
\subsection{Real-Time Communication and Feedback}\label{real-time-communication-and-feedback}}

Once an RA joins the project, they can pose their questions on a CoronaNet Slack channel, which they must join in order to participate in the project. The channel allows any RA to pose a question or issue they may have in using the survey instrument to any of the PIs and allows all other RAs to learn from the exchange at the same time. As such, RAs are able to receive feedback and learn from each other's questions in a timely and centralized manner. Since the data collection effort was launched on March 28, 2020 until April 6, 2020, there were 1,091 messages posted by 108 project members on the Slack channel devoted to asking questions about the Qualtrics survey.

To provide a better sense of the level of activity on the Slack channel, Figure \ref{fig:members} plots the number of project members who had logged into the Slack channel per day as well as the number of project members who posted at least one message per day. This figure shows that participation and activity on the Slack channel has steadily grown over time.\footnote{Note, the dip in the overall trend corresponds to weekend days.}

\begin{figure}
\centering
\includegraphics{corona_wp_files/figure-latex/members -1.pdf}
\caption{(\#fig:members )Plot of the number of Project Members present and active on Slack over time}
\label{fig:members}
\end{figure}

\hypertarget{post-data-collection-validation-checks}{%
\subsection{Post-Data Collection Validation Checks}\label{post-data-collection-validation-checks}}

Lastly, we take the following steps in order to validate the quality of the resulting data collected:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  First, we sample 10\% of the dataset, using the source of the data (e.g.~newspaper article, government press release) as our unit of randomization, to validate. We use the source as our unit of randomization because one source may detail many different policy types.
\item
  Then we then provide these sources to RAs and ask them to code for the government policy based on these sources in a separate, but virtually identical survey instrument. If the source is in a language the RA cannot read, then a new source is drawn.
\item
  We then check for discrepancies between the originally coded data and the second coding of the data in terms of both the number of policies coded and the content of what is coded. If there are no discrepancies, then we consider the data valid. If an RA was found to have made a mistake, then we sample X entries which correspond to the type of mistake made (e.g.~if the RA incorrectly codes an `External Border Restriction' as a `Quarantine', we sample 5 entries where the RA has coded a policy as being about a `Quarantine') and randomly sample X more entries, to ascertain whether the mistake was systematic in nature or not.
\end{enumerate}

Our validation checks reveal that {[}\ldots{}{]}

\hypertarget{dataset}{%
\section{Dataset}\label{dataset}}

Here we present some descriptive statistics to illustrate the type of data that the CoronaNet project is able to provide. Table \ref{tab:desctab} shows the number of records for each policy type, the number of unique countries for each policy type, and also how many countries are targeted in total by each policy type. We would note that these are cumulative totals for these different categories in the data.

\begin{table}[!h]

\caption{\label{tab:desctab}Descriptive Information about the CoronaNet Government Response Dataset}
\centering
\begin{tabular}{>{\raggedright\arraybackslash}p{4cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}}
\toprule
Type & Total Number of Policies & Number of Countries & Number of Targeted Countries & \% With Mandatory Enforcement\\
\midrule
\rowcolor{gray!6}  Closure of Schools & 1050 & 142 & 1 & 87\\
Curfew & 131 & 68 & 13 & 96\\
\rowcolor{gray!6}  Declaration of Emergency & 249 & 92 & 1 & 80\\
External Border Restrictions & 3446 & 172 & 214 & 90\\
\rowcolor{gray!6}  Health Monitoring & 503 & 79 & 201 & 73\\
\addlinespace
Health Resources & 888 & 102 & 105 & 45\\
\rowcolor{gray!6}  Health Testing & 119 & 59 & 48 & 67\\
Internal Border Restrictions & 195 & 83 & 75 & 88\\
\rowcolor{gray!6}  New Task Force or Bureau & 161 & 76 & 1 & 43\\
Other Policy Not Listed Above & 352 & 98 & 1 & 58\\
\addlinespace
\rowcolor{gray!6}  Public Awareness Campaigns & 249 & 97 & 1 & 19\\
Quarantine & 1480 & 133 & 190 & 88\\
\rowcolor{gray!6}  Restriction of Non-Essential Businesses & 867 & 100 & 1 & 89\\
Restriction of Non-Essential Government Services & 119 & 67 & 1 & 78\\
\rowcolor{gray!6}  Restrictions of Mass Gatherings & 421 & 138 & 2 & 86\\
\addlinespace
Social Distancing & 277 & 100 & 2 & 70\\
\bottomrule
\end{tabular}
\end{table}

In addition, we can look at the cumulative indicidence of different types of policies in our data over time, as we show in Figure \ref{fig:overtime}. The figure shows that relatively easy to implement policies like the forming of task forces, public awareness campaigns, and efforts to increase health resources came relatively early. More restrictive policies like curfews, closures of schools and mass gatherings arrived later in the course of the pandemic.

\begin{figure}
\centering
\includegraphics{corona_wp_files/figure-latex/overtime-1.pdf}
\caption{\label{fig:overtime}Cumulative Incidence of Policy Event Types Over Time}
\end{figure}

Of the 4695 events in the dataset, we have identified 4026 unique events. That is, some events in the database are updates or changes to existing policies. We link such events overtime using a unique ID (\texttt{record\_id}). An event counts as an update if it deals with a change in either the:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Time duration or\footnote{An example of (1) is if Germany lengthens its quarantine to 28 days from 14 day.}
\item
  Strength of an existing policy in terms of either\footnote{Examples with regards to (2) is if Germany changes the stringency of an existing quarantine such that: (a) people can no longer leave their houses to go to work whereas before they could (b) the quarantine used to be voluntary but now its mandatory (c) the quarantine used to apply to everyone and now it only applies to the elderly.}

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \tightlist
  \item
    the nature of the policy
  \item
    compliance rules for the policy
  \item
    who the policy applies towards, if applicable.
  \end{enumerate}
\end{enumerate}

A policy counts as a new entry and not an update if it deals with a change in any other dimension, e.g.~policy type, targeted country.

\hypertarget{government-response-severity-index}{%
\section{Government Response Severity Index}\label{government-response-severity-index}}

In this section we briefly present our new index for tracking the relative intensity of government policies targeting COVID-19 across countries and over time. The model is a version of item-response theory that incorporates over-time trends {[}@kubinec2019ideal{]}, permitting inference on how a latent construct, in this case policy stringency, is responding to changes in the pandemic. To fit the model, the different policy types shown in Table \ref{tab:desctab} were coded dichotomously, with a value of 1 if enforcement of the policy was mandatory, and 0 otherwise. As a result, the model estimates whether mandatory policies for each category exist for each country on each day. The country-level stringency score is allowed to vary over time in a random-walk process with a country-specific variance parameter (i.e., to incorporate heteroskedasticity).

The advantage of employing a statistical model, rather than simply summing across policies, is that the index ends up as a weighted average, where the weights are derived by how likely it is that a certain policy is enforced. In other words, while many countries set up task forces, relatively few imposed curfews at an early stage. As a result, the model adjusts for these distinctions, producing a score that aggregates across the patterns in the data.

Furthermore, because the model is stochastic, it is robust to coding errors. As we discuss in our validation section, while we are continuing to validate the data on a daily basis, the massive speed and scope of data collection means that we cannot identify all issues with the data. However, the measurement model employed only requires us to assume that on average the policy codings are correct, not that they are correct for each instance. Coding error, such as incorrectly selecting a policy type, will propogate through the model as higher uncertainty intervals, but will not affect average posterior estimates. As our data quality improves, and we are able to collect more data over time, the model will produce more variegated estimates with smaller uncertainty intervals.

Figure \ref{fig:plotindex} shows the estimated index scores for the 0 countries in our dataset at present. Of course, a caveat with the index is that not all of the possible measures may be coded in the data already due to difficulty in finding the policies in published sources. However, there is still clear differentation within the index in terms of when policies were imposed, with some countries starting to impose policies much earlier than others. Furthermore, there is a clear break about March 1st when countries began to impose more stringent policies across the world.

\begin{figure}
\centering
\includegraphics{corona_wp_files/figure-latex/plotindex-1.pdf}
\caption{\label{fig:plotindex}CoronaNet Time-Varying Index of Severity of Measures Opposing COVID-19 Pandemic}
\end{figure}

Table \ref{tab:rankcount} shows the rank of countries for the index at present. San Marino occupies the highest position, likely because of harsh lockdowns imposed as a result of the outbreak in central Italy. Slovenia has had a nationwide lockdown in place for several weeks, while Azerbaijan took early action to close its borders with Iran in February after the outbreak started. It is important to note the uncertainty in the index measures, as the top 10 countries cannot be distinguished from each other in severity except for San Marino. We believe these uncertainty intervals are important to capture the difficulty in using published policies to compare countries. However, we also see substantial value in this index, particularly in its ability to show change over time.

\begin{longtable}{>{\raggedright\arraybackslash}p{4cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}>{\raggedleft\arraybackslash}p{2.5cm}}
\caption{\label{tab:rankcount}Rank of Countries by Severity Index as of April 3rd, 2020}\\
\toprule
Country & Rank & 5\% Low Score & Median Score & 95\% High Score\\
\midrule
\rowcolor{gray!6}  San Marino & 1 & 76.3 & 82.8 & 90.4\\
Slovenia & 2 & 67.5 & 70.6 & 74.8\\
\rowcolor{gray!6}  Azerbaijan & 3 & 67.3 & 70.5 & 73.7\\
Ireland & 4 & 66.9 & 70.3 & 73.8\\
\rowcolor{gray!6}  Poland & 5 & 66.5 & 69.5 & 72.5\\
\addlinespace
Cuba & 6 & 66.3 & 69.2 & 72.4\\
\rowcolor{gray!6}  Argentina & 7 & 65.4 & 68.9 & 72.6\\
Mexico & 8 & 65.2 & 68.8 & 72.4\\
\rowcolor{gray!6}  Denmark & 9 & 65.5 & 68.7 & 71.9\\
Romania & 10 & 65.7 & 68.6 & 71.9\\
\addlinespace
\rowcolor{gray!6}  Ecuador & 11 & 65.1 & 68.5 & 72.4\\
Netherlands & 12 & 64.4 & 67.6 & 71.1\\
\rowcolor{gray!6}  Croatia & 13 & 65.2 & 67.6 & 70.5\\
Israel & 14 & 64.8 & 67.4 & 70.3\\
\rowcolor{gray!6}  El Salvador & 15 & 64.6 & 67.0 & 70.3\\
\addlinespace
Cyprus & 16 & 63.9 & 67.0 & 70.2\\
\rowcolor{gray!6}  Myanmar & 17 & 63.9 & 66.5 & 69.5\\
Saint Kitts and Nevis & 18 & 62.9 & 66.1 & 69.4\\
\rowcolor{gray!6}  Colombia & 19 & 63.2 & 66.0 & 68.8\\
Hong Kong & 20 & 63.5 & 65.7 & 68.0\\
\addlinespace
\rowcolor{gray!6}  Paraguay & 21 & 62.5 & 65.5 & 68.2\\
Jamaica & 22 & 62.7 & 65.3 & 67.8\\
\rowcolor{gray!6}  Madagascar & 23 & 62.1 & 65.1 & 68.4\\
Tanzania & 24 & 62.1 & 65.0 & 67.8\\
\rowcolor{gray!6}  Burkina Faso & 25 & 61.9 & 64.9 & 67.7\\
\addlinespace
Austria & 26 & 62.1 & 64.9 & 67.8\\
\rowcolor{gray!6}  Latvia & 27 & 62.0 & 64.8 & 67.8\\
Albania & 28 & 61.7 & 64.7 & 67.5\\
\rowcolor{gray!6}  Iran & 29 & 62.3 & 64.7 & 67.4\\
Czechia & 30 & 62.1 & 64.4 & 67.2\\
\addlinespace
\rowcolor{gray!6}  Kuwait & 31 & 61.6 & 64.4 & 67.1\\
Egypt & 32 & 61.8 & 64.3 & 66.9\\
\rowcolor{gray!6}  Estonia & 33 & 61.2 & 64.2 & 67.0\\
United Arab Emirates & 34 & 61.5 & 64.1 & 66.9\\
\rowcolor{gray!6}  Zambia & 35 & 61.2 & 64.0 & 67.2\\
\addlinespace
Italy & 36 & 61.8 & 64.0 & 66.3\\
\rowcolor{gray!6}  Niger & 37 & 61.0 & 63.9 & 66.7\\
Djibouti & 38 & 61.0 & 63.8 & 66.5\\
\rowcolor{gray!6}  Somalia & 39 & 61.0 & 63.6 & 66.3\\
Luxembourg & 40 & 61.2 & 63.6 & 66.4\\
\addlinespace
\rowcolor{gray!6}  Bahamas & 41 & 61.1 & 63.5 & 66.2\\
Mongolia & 42 & 61.2 & 63.5 & 66.2\\
\rowcolor{gray!6}  Ukraine & 43 & 61.1 & 63.5 & 66.2\\
Sudan & 44 & 60.7 & 63.4 & 66.6\\
\rowcolor{gray!6}  Ghana & 45 & 60.9 & 63.4 & 66.0\\
\addlinespace
Iceland & 46 & 60.6 & 63.1 & 66.1\\
\rowcolor{gray!6}  Democratic Republic of the Congo & 47 & 60.5 & 63.1 & 65.9\\
Uganda & 48 & 60.5 & 63.1 & 65.7\\
\rowcolor{gray!6}  North Macedonia & 49 & 60.5 & 63.0 & 65.9\\
Honduras & 50 & 60.3 & 62.9 & 65.5\\
\addlinespace
\rowcolor{gray!6}  Canada & 51 & 61.0 & 62.9 & 65.1\\
Monaco & 52 & 60.5 & 62.9 & 65.6\\
\rowcolor{gray!6}  Iraq & 53 & 60.6 & 62.9 & 65.0\\
France & 54 & 60.4 & 62.9 & 65.5\\
\rowcolor{gray!6}  Sweden & 55 & 60.2 & 62.8 & 65.5\\
\addlinespace
Chile & 56 & 59.8 & 62.7 & 65.4\\
\rowcolor{gray!6}  Bhutan & 57 & 59.9 & 62.7 & 65.3\\
Taiwan & 58 & 60.4 & 62.6 & 65.0\\
\rowcolor{gray!6}  Liechtenstein & 59 & 59.9 & 62.6 & 65.2\\
Belgium & 60 & 59.9 & 62.6 & 65.3\\
\addlinespace
\rowcolor{gray!6}  Pakistan & 61 & 60.2 & 62.4 & 64.6\\
Belarus & 62 & 60.1 & 62.4 & 64.7\\
\rowcolor{gray!6}  Sierra Leone & 63 & 59.9 & 62.4 & 65.1\\
Vietnam & 64 & 60.3 & 62.4 & 64.5\\
\rowcolor{gray!6}  Algeria & 65 & 60.0 & 62.4 & 65.1\\
\addlinespace
Trinidad and Tobago & 66 & 60.2 & 62.3 & 64.4\\
\rowcolor{gray!6}  Papua New Guinea & 67 & 59.4 & 62.3 & 65.2\\
Malawi & 68 & 59.5 & 62.2 & 65.0\\
\rowcolor{gray!6}  Russia & 69 & 60.2 & 61.9 & 63.6\\
Panama & 70 & 59.3 & 61.8 & 64.4\\
\addlinespace
\rowcolor{gray!6}  Mali & 71 & 59.2 & 61.8 & 64.4\\
Comoros & 72 & 59.0 & 61.6 & 64.2\\
\rowcolor{gray!6}  Tonga & 73 & 58.8 & 61.3 & 63.4\\
Switzerland & 74 & 58.5 & 61.2 & 63.6\\
\rowcolor{gray!6}  Germany & 75 & 59.0 & 61.2 & 63.4\\
\addlinespace
Indonesia & 76 & 59.1 & 61.2 & 63.5\\
\rowcolor{gray!6}  Saudi Arabia & 77 & 58.9 & 61.2 & 63.8\\
Namibia & 78 & 58.4 & 61.2 & 63.7\\
\rowcolor{gray!6}  Guyana & 79 & 58.5 & 61.2 & 63.7\\
Lithuania & 80 & 59.0 & 61.0 & 63.4\\
\addlinespace
\rowcolor{gray!6}  Central African Republic & 81 & 57.9 & 60.8 & 63.9\\
Rwanda & 82 & 58.4 & 60.8 & 63.2\\
\rowcolor{gray!6}  Ethiopia & 83 & 58.3 & 60.8 & 63.1\\
Fiji & 84 & 58.2 & 60.6 & 63.1\\
\rowcolor{gray!6}  Mozambique & 85 & 58.2 & 60.6 & 63.1\\
\addlinespace
Finland & 86 & 57.9 & 60.5 & 63.1\\
\rowcolor{gray!6}  Malta & 87 & 58.3 & 60.4 & 62.8\\
Singapore & 88 & 58.9 & 60.3 & 61.8\\
\rowcolor{gray!6}  Brazil & 89 & 58.1 & 60.3 & 62.3\\
Solomon Islands & 90 & 57.5 & 60.1 & 62.5\\
\addlinespace
\rowcolor{gray!6}  Angola & 91 & 57.9 & 60.1 & 62.3\\
Jordan & 92 & 57.1 & 59.9 & 62.4\\
\rowcolor{gray!6}  Greece & 93 & 57.7 & 59.8 & 62.2\\
Kenya & 94 & 57.0 & 59.5 & 61.8\\
\rowcolor{gray!6}  Morocco & 95 & 57.3 & 59.5 & 61.3\\
\addlinespace
Bulgaria & 96 & 56.7 & 59.3 & 61.8\\
\rowcolor{gray!6}  Slovakia & 97 & 56.3 & 59.2 & 61.6\\
Afghanistan & 98 & 56.5 & 59.1 & 61.7\\
\rowcolor{gray!6}  China & 99 & 57.4 & 59.1 & 61.3\\
Timor Leste & 100 & 55.7 & 58.9 & 62.0\\
\addlinespace
\rowcolor{gray!6}  Saint Vincent and the Grenadines & 101 & 56.1 & 58.7 & 61.1\\
New Zealand & 102 & 54.8 & 58.5 & 61.3\\
\rowcolor{gray!6}  India & 103 & 55.7 & 58.5 & 60.6\\
Burundi & 104 & 55.4 & 58.4 & 61.0\\
\rowcolor{gray!6}  Nigeria & 105 & 55.2 & 58.3 & 60.8\\
\addlinespace
Dominica & 106 & 54.9 & 58.2 & 61.1\\
\rowcolor{gray!6}  Moldova & 107 & 54.9 & 58.2 & 60.8\\
Nauru & 108 & 54.9 & 58.0 & 60.8\\
\rowcolor{gray!6}  Guatemala & 109 & 55.4 & 57.9 & 60.0\\
Australia & 110 & 54.6 & 57.4 & 59.5\\
\addlinespace
\rowcolor{gray!6}  Uzbekistan & 111 & 54.4 & 57.3 & 59.6\\
Ivory Coast & 112 & 53.6 & 57.2 & 59.9\\
\rowcolor{gray!6}  Kazakhstan & 113 & 54.7 & 57.1 & 60.0\\
Botswana & 114 & 53.3 & 57.1 & 59.8\\
\rowcolor{gray!6}  Bangladesh & 115 & 53.9 & 56.9 & 60.0\\
\addlinespace
Micronesia & 116 & 53.6 & 56.7 & 59.3\\
\rowcolor{gray!6}  Tuvalu & 117 & 53.7 & 56.5 & 59.0\\
Guinea & 118 & 52.1 & 56.1 & 59.5\\
\rowcolor{gray!6}  Peru & 119 & 51.9 & 55.2 & 58.7\\
Hungary & 120 & 52.0 & 55.2 & 57.7\\
\addlinespace
\rowcolor{gray!6}  Armenia & 121 & 51.5 & 55.1 & 58.9\\
Oman & 122 & 51.1 & 55.1 & 58.3\\
\rowcolor{gray!6}  Kiribati & 123 & 51.6 & 55.0 & 57.7\\
European Union & 124 & 50.7 & 55.0 & 58.3\\
\rowcolor{gray!6}  Japan & 125 & 52.1 & 55.0 & 57.7\\
\addlinespace
Cambodia & 126 & 51.1 & 55.0 & 58.3\\
\rowcolor{gray!6}  United States & 127 & 51.7 & 55.0 & 58.6\\
Vanuatu & 128 & 50.9 & 54.9 & 58.2\\
\rowcolor{gray!6}  Mauritania & 129 & 50.7 & 54.9 & 58.4\\
Mauritius & 130 & 50.7 & 54.7 & 58.4\\
\addlinespace
\rowcolor{gray!6}  Spain & 131 & 50.4 & 54.4 & 58.2\\
Saint Lucia & 132 & 51.1 & 54.3 & 57.4\\
\rowcolor{gray!6}  Turkey & 133 & 49.8 & 53.8 & 57.8\\
Lebanon & 134 & 48.7 & 53.6 & 57.7\\
\rowcolor{gray!6}  South Africa & 135 & 48.2 & 53.2 & 57.3\\
\addlinespace
Nepal & 136 & 48.2 & 52.8 & 56.6\\
\rowcolor{gray!6}  Costa Rica & 137 & 48.8 & 52.3 & 55.5\\
Nicaragua & 138 & 46.8 & 51.8 & 55.5\\
\rowcolor{gray!6}  Grenada & 139 & 46.0 & 51.4 & 55.5\\
North Korea & 140 & 47.9 & 51.1 & 54.6\\
\addlinespace
\rowcolor{gray!6}  Maldives & 141 & 45.5 & 50.7 & 55.2\\
South Korea & 142 & 46.5 & 49.2 & 51.5\\
\bottomrule
\end{longtable}

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

As policymakers, researchers and the broader public debate and compare how to succeed against the novel threats posed by COVID-19, they need real-time, traceable data on government policies in order to understand which of these policies are effective, and under what conditions. This requires specific knowledge of the variation in policies and their implementation. The goal of the dataset and severity index presented hereis to provide this information.

We have tried to match our data collection efforts to keep up with the exponential speed with which the corona-virus has already upended global public health and the international economy while also mainting high levels of quality. However, we will inevitably be refining, revising and updating our data to reflect new knowledge and trends as the pandemic unfolds. The data that we present in this first version of the dataset represents only our initial efforts and we anticipate making ongoing improvements to the dataset over time.

In future work, the CoronaNet team will also provide their own analyses of what drives these responses, under what conditions they can stymy the epidemic, etc., so as to contribute to the social science research community and provide urgently needed knowledge for policymakers and the wider global community.

\hypertarget{appendix}{%
\subsection*{Appendix}\label{appendix}}
\addcontentsline{toc}{subsection}{Appendix}

\hypertarget{codebook}{%
\subsection*{Codebook}\label{codebook}}
\addcontentsline{toc}{subsection}{Codebook}


\end{document}
